### ISSUE TITLE
No subtitles are finding for tv series

### ISSUE THREAD

**Issue by rsoorajs** [Anandpskerala/SubtitlesBot#5]
When we search tv series like ` la casa de papel s06`  or ` game of thrones` there is no results appearing.

just showing `Searching your subtitle file` and results after than.please fix it

**Comment by anandpsdev** [comment]
Its because button data is getting invalid. I am developing an api so that it can be fixed

**Comment by rsoorajs** [comment]
> Its because button data is getting invalid. I am developing an api so that it can be fixed

Waiting.hope the api will be opensource.Thank you
